[phases.setup]
nixPkgs = ["...", "postgresql_16.dev"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.build]

[start]
cmd = "bash start.sh"
